//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItronBankRESTFulService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransaction
    {
        public int TransactionID { get; set; }
        public int AccountId { get; set; }
        public string TransType { get; set; }
        public System.DateTime TransDateTime { get; set; }
        public string TransDesc { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
